# Generated by Django 4.0.6 on 2022-07-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BbCategoriesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(blank=True, null=True)),
                ('detailid', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bb_categories_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbDetailsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bb_details_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('href', models.TextField(blank=True, null=True)),
                ('s3ref', models.TextField(blank=True, null=True)),
                ('primaryimage', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bb_product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtocarturl', models.TextField(blank=True, null=True)),
                ('bestsellingrank', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('customerreviewaverage', models.FloatField(blank=True, null=True)),
                ('customerreviewcount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dollarsavings', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('freeshipping', models.BooleanField(blank=True, null=True)),
                ('includeditems', models.TextField(blank=True, null=True)),
                ('instoreavailability', models.BooleanField(blank=True, null=True)),
                ('instoreavailabilitytext', models.TextField(blank=True, null=True)),
                ('longdescription', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('mobileurl', models.TextField(blank=True, null=True)),
                ('modelnumber', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('onlineavailability', models.BooleanField(blank=True, null=True)),
                ('onlineavailabilitytext', models.TextField(blank=True, null=True)),
                ('onsale', models.BooleanField(blank=True, null=True)),
                ('preowned', models.BooleanField(blank=True, null=True)),
                ('regularprice', models.TextField(blank=True, null=True)),
                ('saleprice', models.TextField(blank=True, null=True)),
                ('shippingcost', models.TextField(blank=True, null=True)),
                ('shortdescription', models.TextField(blank=True, null=True)),
                ('sku', models.TextField(blank=True, null=True)),
                ('thumbnailimage', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('upc', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bb_product_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Databasechangelog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('dateexecuted', models.DateTimeField()),
                ('orderexecuted', models.IntegerField()),
                ('exectype', models.CharField(max_length=10)),
                ('md5sum', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('liquibase', models.CharField(blank=True, max_length=20, null=True)),
                ('contexts', models.CharField(blank=True, max_length=255, null=True)),
                ('labels', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'databasechangelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Databasechangeloglock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('locked', models.BooleanField()),
                ('lockgranted', models.DateTimeField(blank=True, null=True)),
                ('lockedby', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'databasechangeloglock',
                'managed': False,
            },
        ),
    ]
